import { db as adminDb } from "@/firebase/admin";
import { Timestamp, FieldValue } from "firebase-admin/firestore";

export const DEFAULT_PRODUCTS = [
  { 
    id: "frango-assado", 
    nome: "Frango Assado", 
    emoji: "🍗", 
    categoria: "comida", 
    meta: 100, 
    valorPorNumero: 5, 
    premio: 250,
    imagem: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop",
    descricao: "Delicioso frango assado dourado e crocante"
  },
  { 
    id: "carne-assada", 
    nome: "Carne Assada", 
    emoji: "🥩", 
    categoria: "comida", 
    meta: 150, 
    valorPorNumero: 8, 
    premio: 400,
    imagem: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
    descricao: "Carne assada suculenta e temperada"
  },
  { 
    id: "marmita-p", 
    nome: "Marmita P", 
    emoji: "🍱", 
    categoria: "comida", 
    meta: 50, 
    valorPorNumero: 3, 
    premio: 75,
    imagem: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    descricao: "Marmita pequena com arroz, feijão e proteína"
  },
  { 
    id: "marmita-m", 
    nome: "Marmita M", 
    emoji: "🍱", 
    categoria: "comida", 
    meta: 80, 
    valorPorNumero: 5, 
    premio: 150,
    imagem: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop",
    descricao: "Marmita média completa com salada"
  },
  { 
    id: "marmita-g", 
    nome: "Marmita G", 
    emoji: "🍱", 
    categoria: "comida", 
    meta: 100, 
    valorPorNumero: 7, 
    premio: 250,
    imagem: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop",
    descricao: "Marmita grande completa com sobremesa"
  },
];

export function getBadges(rifa: any): string[] {
  const badges: string[] = [];
  const percentComplete = rifa.meta > 0 ? ((rifa.vendidos || 0) / rifa.meta) * 100 : 0;
  const now = Date.now();
  const createdAt = rifa.createdAt?.toDate?.()?.getTime?.() || rifa.createdAt?._seconds * 1000 || 0;
  const timerExpiresAt = rifa.timerExpiresAt?.toDate?.()?.getTime?.() || rifa.timerExpiresAt?._seconds * 1000 || 0;

  if (rifa.status === "contagem" || (timerExpiresAt > 0 && timerExpiresAt > now)) {
    badges.push("ultimos-momentos");
  }

  if (percentComplete >= 80 && rifa.status === "aberta") {
    badges.push("quase-esgotada");
  }

  if (now - createdAt < 30 * 60 * 1000) {
    badges.push("nova-rodada");
  }

  if ((rifa.comprasRecentes || 0) > 5) {
    badges.push("popular");
  }

  return badges;
}

export async function isAutoRifaEnabled(): Promise<boolean> {
  if (!adminDb) return false;
  try {
    const configDoc = await adminDb.collection("config").doc("autoRifa").get();
    return configDoc.exists && configDoc.data()?.enabled === true;
  } catch {
    return false;
  }
}

export async function createRifaForProduct(product: typeof DEFAULT_PRODUCTS[0]): Promise<string | null> {
  if (!adminDb) return null;

  try {
    const rifaData = {
      nome: `${product.emoji} ${product.nome}`,
      categoria: product.categoria,
      meta: product.meta,
      vendidos: 0,
      valorPorNumero: product.valorPorNumero,
      premio: product.premio,
      status: "aberta",
      productId: product.id,
      autoGenerated: true,
      imagem: product.imagem,
      descricao: product.descricao,
      createdAt: FieldValue.serverTimestamp(),
      updatedAt: FieldValue.serverTimestamp(),
      numerosComprados: [],
      comprasRecentes: 0,
      lastActivityAt: FieldValue.serverTimestamp(),
    };

    const docRef = await adminDb.collection("rifas").add(rifaData);
    console.log(`[AutoRifa] Created new rifa for ${product.nome}: ${docRef.id}`);
    return docRef.id;
  } catch (err) {
    console.error(`[AutoRifa] Error creating rifa for ${product.nome}:`, err);
    return null;
  }
}

export async function ensureAllProductsHaveActiveRifas(): Promise<void> {
  if (!adminDb) return;

  const enabled = await isAutoRifaEnabled();
  if (!enabled) return;

  try {
    const activeSnap = await adminDb.collection("rifas").where("status", "in", ["aberta", "contagem"]).get();
    const activeProductIds = new Set<string>();

    activeSnap.docs.forEach((doc) => {
      const data = doc.data();
      if (data.productId) {
        activeProductIds.add(data.productId);
      }
    });

    for (const product of DEFAULT_PRODUCTS) {
      if (!activeProductIds.has(product.id)) {
        await createRifaForProduct(product);
      }
    }
  } catch (err) {
    console.error("[AutoRifa] Error ensuring products have rifas:", err);
  }
}

export async function checkAndBoostStagnantRifas(): Promise<void> {
  if (!adminDb) return;

  const enabled = await isAutoRifaEnabled();
  if (!enabled) return;

  try {
    const rifasSnap = await adminDb.collection("rifas").where("status", "==", "aberta").get();
    const now = Date.now();

    for (const rifaDoc of rifasSnap.docs) {
      const rifa = rifaDoc.data();
      const percentComplete = rifa.meta > 0 ? ((rifa.vendidos || 0) / rifa.meta) * 100 : 0;
      const lastActivity = rifa.lastActivityAt?.toDate?.()?.getTime?.() || rifa.updatedAt?.toDate?.()?.getTime?.() || 0;
      const stagnantMinutes = (now - lastActivity) / (1000 * 60);

      if (percentComplete >= 80 && stagnantMinutes >= 5) {
        const remaining = rifa.meta - (rifa.vendidos || 0);
        const boost = Math.min(remaining, Math.ceil(remaining * 0.3));

        if (boost > 0) {
          const existingNumeros = rifa.numerosComprados || [];
          const startNum = (rifa.vendidos || 0) + 1;
          const syntheticEntries = Array.from({ length: boost }, (_, i) => ({
            numero: startNum + i,
            userId: "system-boost",
            synthetic: true,
            createdAt: new Date(),
          }));

          await adminDb.collection("rifas").doc(rifaDoc.id).update({
            vendidos: FieldValue.increment(boost),
            numerosComprados: [...existingNumeros, ...syntheticEntries],
            lastActivityAt: FieldValue.serverTimestamp(),
            updatedAt: FieldValue.serverTimestamp(),
          });
          console.log(`[AutoRifa] Boosted rifa ${rifaDoc.id} by ${boost} numbers with synthetic entries`);
        }
      }
    }
  } catch (err) {
    console.error("[AutoRifa] Error boosting stagnant rifas:", err);
  }
}

export async function checkGoalReachedRifas(): Promise<void> {
  if (!adminDb) return;

  const enabled = await isAutoRifaEnabled();
  if (!enabled) return;

  try {
    const rifasSnap = await adminDb.collection("rifas").where("status", "==", "aberta").get();

    for (const doc of rifasSnap.docs) {
      const rifa = doc.data();

      if ((rifa.vendidos || 0) >= rifa.meta) {
        const timerExpiresAt = Timestamp.fromDate(new Date(Date.now() + 10 * 60 * 1000));
        
        await adminDb.collection("rifas").doc(doc.id).update({
          status: "contagem",
          timerExpiresAt,
          updatedAt: FieldValue.serverTimestamp(),
        });
        console.log(`[AutoRifa] Rifa ${doc.id} reached goal, starting 10-minute countdown`);
      }
    }
  } catch (err) {
    console.error("[AutoRifa] Error checking goal reached:", err);
  }
}

export async function processExpiredCountdowns(): Promise<void> {
  if (!adminDb) return;

  const enabled = await isAutoRifaEnabled();
  if (!enabled) return;

  try {
    const now = Timestamp.now();
    const rifasSnap = await adminDb.collection("rifas")
      .where("status", "==", "contagem")
      .where("timerExpiresAt", "<=", now)
      .get();

    for (const doc of rifasSnap.docs) {
      const rifa = doc.data();

      const numerosComprados = rifa.numerosComprados || [];
      let winner = null;
      let winnerNumber = null;

      if (numerosComprados.length > 0) {
        const seed = `${doc.id}-${Date.now()}-${Math.random()}`;
        const crypto = await import("crypto");
        const hash = crypto.createHash("sha256").update(seed).digest("hex");
        const randomIndex = parseInt(hash.slice(0, 8), 16) % numerosComprados.length;
        const winningEntry = numerosComprados[randomIndex];
        winner = winningEntry.userId || winningEntry;
        winnerNumber = winningEntry.numero || randomIndex + 1;
      }

      await adminDb.collection("rifas").doc(doc.id).update({
        status: "finalizado",
        winner,
        winnerNumber,
        sortedAt: FieldValue.serverTimestamp(),
        updatedAt: FieldValue.serverTimestamp(),
      });

      await adminDb.collection("historico").add({
        rifaId: doc.id,
        rifaNome: rifa.nome,
        winner,
        winnerNumber,
        premio: rifa.premio,
        totalVendidos: rifa.vendidos,
        sortedAt: FieldValue.serverTimestamp(),
      });

      console.log(`[AutoRifa] Rifa ${doc.id} finished, winner: ${winner}, number: ${winnerNumber}`);

      if (rifa.productId) {
        const product = DEFAULT_PRODUCTS.find((p) => p.id === rifa.productId);
        if (product) {
          await createRifaForProduct(product);
        }
      }
    }
  } catch (err) {
    console.error("[AutoRifa] Error processing expired countdowns:", err);
  }
}

export async function runAutoRifaCycle(): Promise<{ processed: boolean; message: string }> {
  const enabled = await isAutoRifaEnabled();
  if (!enabled) {
    return { processed: false, message: "Auto-rifa is disabled" };
  }

  await ensureAllProductsHaveActiveRifas();
  await checkGoalReachedRifas();
  await checkAndBoostStagnantRifas();
  await processExpiredCountdowns();

  return { processed: true, message: "Auto-rifa cycle completed" };
}
