"use client";
import React, { useEffect, useState, useMemo } from "react";
import { db } from "@/firebase/client";
import { collection, query, orderBy, onSnapshot } from "firebase/firestore";
import { useCart } from "@/components/CartContext";

interface Rifa {
  id: string;
  nome: string;
  vendidos?: number;
  meta?: number;
  valorPorNumero?: number;
  valor?: number;
  timerExpiresAt?: string;
  status?: string;
  categoria?: string;
  desconto?: number;
  createdAt?: any;
  comprasRecentes?: number;
  autoGenerated?: boolean;
  descricao?: string;
  imagem?: string;
}

const CATEGORIAS_DEFAULT = [
  { id: "todas", label: "Todas", emoji: "🎯" },
  { id: "comida", label: "Comida", emoji: "🍗" },
  { id: "eletronicos", label: "Eletrônicos", emoji: "📱" },
  { id: "veiculos", label: "Veículos", emoji: "🚗" },
  { id: "dinheiro", label: "Dinheiro", emoji: "💵" },
  { id: "experiencias", label: "Experiências", emoji: "✈️" },
  { id: "outros", label: "Outros", emoji: "🎁" },
];

function getBadges(rifa: Rifa): { label: string; color: string; icon: string }[] {
  const badges: { label: string; color: string; icon: string }[] = [];
  const percentComplete = (rifa.meta || 1) > 0 ? ((rifa.vendidos || 0) / (rifa.meta || 1)) * 100 : 0;
  const now = Date.now();
  const createdAt = rifa.createdAt?.toDate?.()?.getTime?.() || rifa.createdAt?.seconds * 1000 || 0;
  const timerExpiresAt = rifa.timerExpiresAt ? new Date(rifa.timerExpiresAt).getTime() : 0;

  if (rifa.status === "contagem" || (timerExpiresAt > 0 && timerExpiresAt > now && timerExpiresAt - now < 10 * 60 * 1000)) {
    badges.push({ label: "Últimos Momentos", color: "bg-red-500 text-white", icon: "🔥" });
  }

  if (percentComplete >= 80 && rifa.status === "aberta") {
    badges.push({ label: "Quase Esgotada", color: "bg-orange-500 text-white", icon: "⚡" });
  }

  if (createdAt && now - createdAt < 30 * 60 * 1000) {
    badges.push({ label: "Nova Rodada", color: "bg-blue-500 text-white", icon: "♻️" });
  }

  if ((rifa.comprasRecentes || 0) > 5) {
    badges.push({ label: "Popular", color: "bg-purple-500 text-white", icon: "⭐" });
  }

  return badges;
}

export default function AllRifasGrid() {
  const [rifas, setRifas] = useState<Rifa[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeFilter, setActiveFilter] = useState("todas");
  const cart = useCart();

  useEffect(() => {
    if (!db) return;
    const q = query(collection(db, "rifas"), orderBy("createdAt", "desc"));
    const unsub = onSnapshot(
      q,
      (snap) => {
        setRifas(snap.docs.map((d) => ({ id: d.id, ...d.data() } as Rifa)));
        setLoading(false);
      },
      (err) => {
        console.error("rifas:onSnapshot", err);
        setLoading(false);
      }
    );
    return () => unsub();
  }, []);

  const categories = useMemo(() => {
    const uniqueCats = new Set(rifas.map((r) => r.categoria || "outros"));
    return CATEGORIAS_DEFAULT.filter(
      (c) => c.id === "todas" || uniqueCats.has(c.id)
    );
  }, [rifas]);

  const filteredRifas = useMemo(() => {
    // Filtrar rifas que NÃO estão em contagem, encerrada ou finalizado
    // Essas vão para o componente "Prestes a Sortear"
    const rifasAtivas = rifas.filter((r) => 
      r.status !== "contagem" && 
      r.status !== "encerrada" && 
      r.status !== "finalizado"
    );
    
    if (activeFilter === "todas") return rifasAtivas;
    return rifasAtivas.filter((r) => (r.categoria || "outros") === activeFilter);
  }, [rifas, activeFilter]);

  if (loading) {
    return (
      <section className="mb-8">
        <div className="flex items-center gap-2 mb-4">
          <span className="text-2xl">🎰</span>
          <h2 className="text-xl font-bold text-gray-800">Todas as Rifas</h2>
        </div>
        <div className="flex gap-2 mb-6 overflow-x-auto pb-2">
          {[1, 2, 3, 4, 5].map((i) => (
            <div key={i} className="bg-gray-200 rounded-full h-10 w-24 animate-pulse flex-shrink-0" />
          ))}
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {[1, 2, 3, 4, 5, 6].map((i) => (
            <div key={i} className="bg-gray-200 rounded-xl h-52 animate-pulse" />
          ))}
        </div>
      </section>
    );
  }

  return (
    <section className="mb-8">
      <div className="flex items-center gap-2 mb-4">
        <span className="text-2xl">🎰</span>
        <h2 className="text-xl font-bold text-gray-800">Todas as Rifas</h2>
        <span className="ml-2 text-sm text-gray-500">
          ({filteredRifas.length} disponíveis)
        </span>
      </div>

      <div className="flex gap-2 mb-6 overflow-x-auto pb-2 scrollbar-hide">
        {categories.map((cat) => (
          <button
            key={cat.id}
            onClick={() => setActiveFilter(cat.id)}
            className={`flex items-center gap-2 px-4 py-2 rounded-full font-medium text-sm whitespace-nowrap transition-all duration-200 flex-shrink-0 ${
              activeFilter === cat.id
                ? "bg-green-600 text-white shadow-md"
                : "bg-white text-gray-700 border border-gray-200 hover:border-green-400 hover:bg-green-50"
            }`}
          >
            <span>{cat.emoji}</span>
            <span>{cat.label}</span>
          </button>
        ))}
      </div>

      {filteredRifas.length === 0 ? (
        <div className="text-center py-12 bg-gray-50 rounded-xl">
          <span className="text-4xl mb-4 block">🔍</span>
          <p className="text-gray-500">Nenhuma rifa encontrada nesta categoria</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredRifas.map((rifa) => {
            const progresso = Math.round(((rifa.vendidos || 0) / (rifa.meta || 1)) * 100);
            const disponivel = (rifa.meta || 100) - (rifa.vendidos || 0);
            const esgotado = disponivel <= 0;
            const quaseAcabando = progresso >= 80;
            const desconto = rifa.desconto || (progresso >= 90 ? 10 : 0);
            const precoOriginal = rifa.valorPorNumero || rifa.valor || 10;
            const precoComDesconto = desconto
              ? precoOriginal * (1 - desconto / 100)
              : precoOriginal;
            const tempoRestante = rifa.timerExpiresAt
              ? `${Math.max(0, Math.floor((new Date(rifa.timerExpiresAt).getTime() - Date.now()) / 60000))} min`
              : "--";

            const handleAdd = (e: React.MouseEvent) => {
              e.preventDefault();
              // Verificar se esgotou (vendidos >= meta)
              if ((rifa.vendidos || 0) >= (rifa.meta || 100)) {
                alert('Esta rifa já esgotou!');
                return;
              }
              if (esgotado) {
                alert('Esta rifa já esgotou!');
                return;
              }
              // Verificar quantidade já no carrinho
              const noCarrinho = cart.items.find(i => i.rifaId === rifa.id)?.quantidade || 0;
              if (noCarrinho >= disponivel) {
                alert(`Você já tem ${noCarrinho} no carrinho. Só restam ${disponivel} números disponíveis.`);
                return;
              }
              cart.addItem({
                rifaId: rifa.id,
                nome: rifa.nome,
                quantidade: 1,
                valorPorNumero: precoOriginal,
              });
            };

            const rifaBadges = getBadges(rifa);
            return (
              <div
                key={rifa.id}
                className="group bg-white rounded-xl shadow-sm hover:shadow-xl border border-gray-100 overflow-hidden transition-all duration-300 hover:-translate-y-1 flex flex-col"
              >
                {/* Miniatura da imagem */}
                {rifa.imagem && (
                  <div className="relative h-32 w-full overflow-hidden flex-shrink-0">
                    <img
                      src={rifa.imagem}
                      alt={rifa.nome}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                    />
                    {esgotado && (
                      <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                        <span className="text-white font-bold text-lg">ESGOTADO</span>
                      </div>
                    )}
                  </div>
                )}
                <div className="p-4 flex flex-col flex-1">
                  <div className="flex items-start justify-between mb-2">
                    <h3 className="font-bold text-gray-800 group-hover:text-green-600 transition truncate flex-1">
                      {rifa.nome}
                    </h3>
                    {desconto > 0 && (
                      <span className="ml-2 px-2 py-0.5 bg-green-100 text-green-700 text-xs font-semibold rounded-full animate-bounce">
                        -{desconto}%
                      </span>
                    )}
                  </div>

                  {rifa.descricao && (
                    <p className="text-gray-500 text-sm mb-2 line-clamp-2">
                      {rifa.descricao}
                    </p>
                  )}

                  {rifaBadges.length > 0 && (
                    <div className="flex flex-wrap gap-1 mb-2">
                      {rifaBadges.map((badge, idx) => (
                        <span
                          key={idx}
                          className={`inline-flex items-center gap-1 px-2 py-0.5 text-xs font-semibold rounded-full ${badge.color} ${badge.label === "Últimos Momentos" ? "animate-pulse" : ""}`}
                        >
                          {badge.icon} {badge.label}
                        </span>
                      ))}
                    </div>
                  )}

                  {/* Prêmio removido do card */}

                  <div className="flex items-center gap-2 text-xs text-gray-500 mb-2">
                    <span>🛒 {rifa.vendidos || 0}/{rifa.meta || 0}</span>
                    {disponivel > 0 && disponivel <= 10 && (
                      <span className="text-red-500 font-semibold">Restam {disponivel}!</span>
                    )}
                    <span className="ml-auto">⏱️ {tempoRestante}</span>
                  </div>

                  <div className="w-full bg-gray-200 rounded-full h-2 mb-3">
                    <div
                      className={`h-2 rounded-full transition-all duration-500 ${
                        quaseAcabando
                          ? "bg-gradient-to-r from-red-400 to-red-600"
                          : "bg-gradient-to-r from-green-400 to-green-600"
                      }`}
                      style={{ width: `${progresso}%` }}
                    />
                  </div>

                  <div className="mt-auto flex items-center justify-between">
                    <div className="flex items-baseline gap-2">
                      <span className="text-lg font-bold text-green-700">
                        R$ {precoComDesconto.toFixed(2)}
                      </span>
                      {desconto > 0 && (
                        <span className="text-sm line-through text-gray-400">
                          R$ {precoOriginal.toFixed(2)}
                        </span>
                      )}
                    </div>
                    <button
                      onClick={handleAdd}
                      disabled={esgotado}
                      className={`px-3 py-2 text-sm font-semibold rounded-lg shadow transition-all flex items-center gap-1 ${
                        esgotado 
                          ? 'bg-gray-400 cursor-not-allowed text-gray-200' 
                          : 'bg-green-600 hover:bg-green-700 text-white'
                      }`}
                    >
                      <span>🛒</span> {esgotado ? 'Esgotado' : 'Adicionar'}
                    </button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </section>
  );
}
